name: Deploy to Server

on:
  push:
    branches:
      - main  # 'deploy' 브랜치에 push될 때 실행됨

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      # Set up Docker Buildx
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      # Docker login to Docker Hub
      - name: Docker login to Docker Hubs
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}   # Docker Hub 사용자명
          password: ${{ secrets.DOCKER_PASSWORD }}   # Docker Hub 비밀번호

      # Build Docker image
      - name: Build Docker Image
        run: mvn clean install -DskipTests

      # Push Docker image to Docker Hub
      - name: Push Docker Image to Docker Hub
        run: |
          docker build -t ${{ secrets.DOCKER_USERNAME }}/cicdmyapp-eureka:latest .
          docker push ${{ secrets.DOCKER_USERNAME }}/cicdmyapp-eureka:latest




